# Generated by Django 2.2.6 on 2019-11-02 07:40

import core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match_id', models.IntegerField(verbose_name='match id')),
                ('inning', models.IntegerField(verbose_name='inning')),
                ('batting_team', models.CharField(max_length=50, verbose_name='batting team')),
                ('bowling_team', models.CharField(max_length=50, verbose_name='bowling team')),
                ('over', models.IntegerField(verbose_name='over')),
                ('ball', models.IntegerField(validators=[core.validators.validate_ball_in_over], verbose_name='ball')),
                ('batsman', models.CharField(max_length=50, verbose_name='batsman')),
                ('non_striker', models.CharField(max_length=50, verbose_name='non striker')),
                ('bowler', models.CharField(max_length=50, verbose_name='bowler')),
                ('is_super_over', models.BooleanField(default=False, verbose_name='is super over')),
                ('wide_run', models.IntegerField(verbose_name='wide run')),
                ('bye_run', models.IntegerField(verbose_name='bye runs')),
                ('legbye_run', models.IntegerField(verbose_name='legbye runs')),
                ('penalty_run', models.IntegerField(verbose_name='penalty runs')),
                ('batsman_run', models.IntegerField(verbose_name='batsman runs')),
                ('extra_run', models.IntegerField(verbose_name='extra runs')),
                ('total_run', models.IntegerField(verbose_name='total runs')),
                ('player_dismissed', models.CharField(max_length=50, verbose_name='player dismissed')),
                ('dismissed_kind', models.CharField(max_length=25, verbose_name='dismissed kind')),
                ('fielder', models.CharField(max_length=50, verbose_name='fielder')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match_id', models.IntegerField(verbose_name='match id')),
                ('season', models.IntegerField(validators=[core.validators.validate_year], verbose_name='season')),
                ('match_date', models.DateField(verbose_name='match date')),
                ('team1', models.CharField(max_length=50, verbose_name='team 1')),
                ('team2', models.CharField(max_length=50, verbose_name='team 2')),
                ('toss_winner', models.CharField(max_length=50, verbose_name='toss_winner')),
                ('toss_decision', models.CharField(max_length=10, verbose_name='toss_decision')),
                ('result', models.CharField(max_length=10, verbose_name='result')),
                ('dl_applied', models.IntegerField(verbose_name='dl_applied')),
                ('winner', models.CharField(max_length=50, verbose_name='winner')),
                ('wins_by_run', models.IntegerField(verbose_name='wins by run')),
                ('wins_by_wicket', models.IntegerField(verbose_name='wins by wicket')),
                ('player_of_match', models.CharField(max_length=50, verbose_name='player of match')),
                ('venue', models.CharField(max_length=100, verbose_name='venue')),
                ('umpire1', models.CharField(max_length=50, verbose_name='umpire 1')),
                ('umpire2', models.CharField(max_length=50, verbose_name='umpire 1')),
                ('umpire3', models.CharField(blank=True, max_length=50, null=True, verbose_name='umpire 1')),
            ],
            options={
                'db_table': 'match',
            },
        ),
    ]
