# Generated by Django 2.2.6 on 2019-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wins_by_run',
            new_name='wins_by_runs',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wins_by_wicket',
            new_name='wins_by_wickets',
        ),
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(default='', max_length=60, verbose_name='city'),
            preserve_default=False,
        ),
    ]
