# Generated by Django 2.2.6 on 2019-11-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20191102_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='wins_by_runs',
            new_name='win_by_runs',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wins_by_wickets',
            new_name='win_by_wickets',
        ),
    ]
