# Generated by Django 2.2.6 on 2019-11-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20191102_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='batsman_run',
            new_name='batsman_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='bye_run',
            new_name='bye_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='extra_run',
            new_name='extra_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='legbye_run',
            new_name='legbye_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='penalty_run',
            new_name='penalty_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='total_run',
            new_name='total_runs',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='wide_run',
            new_name='wide_runs',
        ),
    ]
