# Generated by Django 2.2.6 on 2019-11-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20191102_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='dismissed_kind',
            new_name='dismissal_kind',
        ),
    ]
