# Generated by Django 2.2.6 on 2019-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20191102_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='noball_runs',
            field=models.IntegerField(default=0, verbose_name='noball_runs'),
            preserve_default=False,
        ),
    ]
