# Generated by Django 2.2.6 on 2019-11-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_delivery_noball_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match', verbose_name='match id'),
        ),
    ]
